-- Add EXPIRED to BookingStatus enums

ALTER TABLE `Booking`
  MODIFY `status` ENUM('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING';

ALTER TABLE `BookingStatusHistory`
  MODIFY `oldStatus` ENUM('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'EXPIRED') NOT NULL,
  MODIFY `newStatus` ENUM('PENDING', 'CONFIRMED', 'FAILED', 'CANCELLED', 'EXPIRED') NOT NULL;
